from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CosmeticDefinition:
    id: str
    name: str
    category: str
    rarity: str
    asset_url: str
    description: str
    unlock_hint: str
    requirement_type: str
    requirement_value: int
    price: int
    is_purchasable: bool


COSMETIC_CATALOG = [
    CosmeticDefinition(
        id="avatar-matgo-owl",
        name="Coruja MatGo",
        category="avatar",
        rarity="comum",
        asset_url="/oficial.png",
        description="Mascote oficial da plataforma para todo aluno comecar sua jornada.",
        unlock_hint="Mascote base da plataforma",
        requirement_type="default",
        requirement_value=0,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-explorador",
        name="Explorador Azul",
        category="avatar",
        rarity="comum",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoExplorador",
        description="Visual inicial de quem ja deu os primeiros passos com constancia.",
        unlock_hint="Disponivel a partir do nivel 2",
        requirement_type="level",
        requirement_value=2,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-streak",
        name="Aura de Streak",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoFogo",
        description="Visual de quem conseguiu criar ritmo e constancia na plataforma.",
        unlock_hint="Liberado com streak de 7 dias",
        requirement_type="streak",
        requirement_value=7,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-gemas",
        name="Guardiao de Gemas",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoGema",
        description="Visual de colecionador para quem juntou moedas e evoluiu no jogo.",
        unlock_hint="Liberado com 400 moedas",
        requirement_type="coins",
        requirement_value=400,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-astro",
        name="Avatar Astro",
        category="avatar",
        rarity="epico",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoAstro",
        description="Item epico para alunos com progresso alto e consistencia real.",
        unlock_hint="Liberado com 1500 XP e streak de 7 dias",
        requirement_type="xp_streak_combo",
        requirement_value=1500,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-neon",
        name="Neon Runner",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoNeon",
        description="Avatar vibrante para quem quer aparecer no ranking.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=180,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="avatar-cientista",
        name="Mini Cientista",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoCientista",
        description="Visual de laboratorio para quem gosta de progresso tecnico.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=240,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="avatar-piloto",
        name="Piloto Solar",
        category="avatar",
        rarity="epico",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoPiloto",
        description="Avatar epico para alunos que querem um visual mais raro sem depender so de streak.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=420,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-aurora",
        name="Tema Aurora",
        category="theme",
        rarity="raro",
        asset_url="theme-aurora",
        description="Gradientes energeticos para estudar com estilo.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=160,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-floresta",
        name="Tema Floresta",
        category="theme",
        rarity="comum",
        asset_url="theme-floresta",
        description="Paleta verde clara inspirada no mascote da MatGo.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=120,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-cosmos",
        name="Tema Cosmos",
        category="theme",
        rarity="epico",
        asset_url="theme-cosmos",
        description="Visual espacial para quem quer deixar a plataforma com cara de desafio avancado.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=360,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-solar",
        name="Tema Solar",
        category="theme",
        rarity="raro",
        asset_url="theme-solar",
        description="Paleta quente para uma identidade mais viva na interface.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=210,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-padrao",
        name="Moldura Padrao",
        category="frame",
        rarity="comum",
        asset_url="frame-padrao",
        description="Visual limpo e elegante para destacar o card principal do perfil.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=180,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-bronze",
        name="Moldura Bronze",
        category="frame",
        rarity="comum",
        asset_url="frame-bronze",
        description="Acabamento quente com brilho metalico leve para um perfil em ascensao.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=260,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-prata",
        name="Moldura Prata",
        category="frame",
        rarity="raro",
        asset_url="frame-prata",
        description="Visual polido e premium com reflexos frios para perfis consistentes.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=340,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-ouro",
        name="Moldura Ouro",
        category="frame",
        rarity="raro",
        asset_url="frame-ouro",
        description="Acabamento dourado para transformar o perfil em uma conquista visivel.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=480,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-cristal",
        name="Moldura Cristal",
        category="frame",
        rarity="raro",
        asset_url="frame-cristal",
        description="Camadas translucidas e reflexos suaves que deixam o card mais refinado.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=520,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-galaxia",
        name="Moldura Galaxia",
        category="frame",
        rarity="epico",
        asset_url="frame-galaxia",
        description="Energia espacial com brilho profundo para perfis memoraveis.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=760,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-matematica",
        name="Moldura Matematica",
        category="frame",
        rarity="raro",
        asset_url="frame-matematica",
        description="Detalhes inspirados em graficos, formulas e ritmo de estudo.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=610,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-mestre",
        name="Moldura Mestre",
        category="frame",
        rarity="epico",
        asset_url="frame-mestre",
        description="A skin mais nobre do card principal, com presença forte e acabamento de elite.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=980,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-aura-pop",
        name="Moldura Aura Pop",
        category="frame",
        rarity="raro",
        asset_url="frame-aura-pop",
        description="Cores contagiantes com brilho alegre e kaomojis discretos no card principal.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=680,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-elegancia-neon",
        name="Moldura Elegancia Neon",
        category="frame",
        rarity="epico",
        asset_url="frame-elegancia-neon",
        description="Mistura refinada de neon suave com emoticons sutis para um visual sofisticado.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=920,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="frame-brilho-estudo",
        name="Moldura Brilho de Estudo",
        category="frame",
        rarity="comum",
        asset_url="frame-padrao",
        description="Versao classica de entrada para o card do perfil.",
        unlock_hint="Moldura legada da plataforma",
        requirement_type="default",
        requirement_value=0,
        price=140,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="frame-esmeralda",
        name="Moldura Esmeralda",
        category="frame",
        rarity="raro",
        asset_url="frame-cristal",
        description="Versao legada preservada para perfis antigos.",
        unlock_hint="Moldura legada da plataforma",
        requirement_type="default",
        requirement_value=0,
        price=260,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="frame-cosmos",
        name="Moldura Cosmos",
        category="frame",
        rarity="epico",
        asset_url="frame-galaxia",
        description="Versao legada preservada para perfis antigos.",
        unlock_hint="Moldura legada da plataforma",
        requirement_type="default",
        requirement_value=0,
        price=430,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="powerup-vida-extra",
        name="+1 Vida",
        category="powerup",
        rarity="comum",
        asset_url="powerup-vida-extra",
        description="Recupere uma vida para continuar a rotina sem travar.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=110,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="powerup-dica-plus",
        name="Dica Plus",
        category="powerup",
        rarity="comum",
        asset_url="powerup-dica-plus",
        description="Ative uma dica extra em uma questao da missao diaria.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=90,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="powerup-escudo-streak",
        name="Escudo de Streak",
        category="powerup",
        rarity="epico",
        asset_url="powerup-escudo-streak",
        description="Protege um dia de streak caso voce erre ou perca a sequencia.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=350,
        is_purchasable=True,
    ),
]
