from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CosmeticDefinition:
    id: str
    name: str
    category: str
    rarity: str
    asset_url: str
    description: str
    unlock_hint: str
    requirement_type: str
    requirement_value: int
    price: int
    is_purchasable: bool


COSMETIC_CATALOG = [
    CosmeticDefinition(
        id="avatar-matgo-owl",
        name="Coruja MatGo",
        category="avatar",
        rarity="comum",
        asset_url="/oficial.png",
        description="Mascote oficial da plataforma para todo aluno comecar sua jornada.",
        unlock_hint="Mascote base da plataforma",
        requirement_type="default",
        requirement_value=0,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-explorador",
        name="Explorador Azul",
        category="avatar",
        rarity="comum",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoExplorador",
        description="Visual inicial de quem ja deu os primeiros passos com constancia.",
        unlock_hint="Disponivel a partir do nivel 2",
        requirement_type="level",
        requirement_value=2,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-streak",
        name="Aura de Streak",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoFogo",
        description="Visual de quem conseguiu criar ritmo e constancia na plataforma.",
        unlock_hint="Liberado com streak de 7 dias",
        requirement_type="streak",
        requirement_value=7,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-gemas",
        name="Guardiao de Gemas",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoGema",
        description="Visual de colecionador para quem juntou moedas e evoluiu no jogo.",
        unlock_hint="Liberado com 400 moedas",
        requirement_type="coins",
        requirement_value=400,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-astro",
        name="Avatar Astro",
        category="avatar",
        rarity="epico",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoAstro",
        description="Item epico para alunos com progresso alto e consistencia real.",
        unlock_hint="Liberado com 1500 XP e streak de 7 dias",
        requirement_type="xp_streak_combo",
        requirement_value=1500,
        price=0,
        is_purchasable=False,
    ),
    CosmeticDefinition(
        id="avatar-neon",
        name="Neon Runner",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoNeon",
        description="Avatar vibrante para quem quer aparecer no ranking.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=180,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="avatar-cientista",
        name="Mini Cientista",
        category="avatar",
        rarity="raro",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoCientista",
        description="Visual de laboratorio para quem gosta de progresso tecnico.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=240,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="avatar-piloto",
        name="Piloto Solar",
        category="avatar",
        rarity="epico",
        asset_url="https://api.dicebear.com/8.x/adventurer/svg?seed=MatGoPiloto",
        description="Avatar epico para alunos que querem um visual mais raro sem depender so de streak.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=420,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-aurora",
        name="Tema Aurora",
        category="theme",
        rarity="raro",
        asset_url="theme-aurora",
        description="Gradientes energeticos para estudar com estilo.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=160,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-floresta",
        name="Tema Floresta",
        category="theme",
        rarity="comum",
        asset_url="theme-floresta",
        description="Paleta verde clara inspirada no mascote da MatGo.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=120,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-cosmos",
        name="Tema Cosmos",
        category="theme",
        rarity="epico",
        asset_url="theme-cosmos",
        description="Visual espacial para quem quer deixar a plataforma com cara de desafio avancado.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=360,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="theme-solar",
        name="Tema Solar",
        category="theme",
        rarity="raro",
        asset_url="theme-solar",
        description="Paleta quente para uma identidade mais viva na interface.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=210,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="powerup-vida-extra",
        name="+1 Vida",
        category="powerup",
        rarity="comum",
        asset_url="powerup-vida-extra",
        description="Recupere uma vida para continuar a rotina sem travar.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=110,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="powerup-dica-plus",
        name="Dica Plus",
        category="powerup",
        rarity="comum",
        asset_url="powerup-dica-plus",
        description="Ative uma dica extra em uma questao da missao diaria.",
        unlock_hint="Disponivel na loja",
        requirement_type="shop_only",
        requirement_value=0,
        price=90,
        is_purchasable=True,
    ),
    CosmeticDefinition(
        id="powerup-escudo-streak",
        name="Escudo de Streak",
        category="powerup",
        rarity="epico",
        asset_url="powerup-escudo-streak",
        description="Protege um dia de streak caso voce erre ou perca a sequencia.",
        unlock_hint="Disponivel na loja premium",
        requirement_type="shop_only",
        requirement_value=0,
        price=350,
        is_purchasable=True,
    ),
]
